
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
  config-location: classpath:/mybatis-config.xml
server:
  port: 10000
logging:
  level:
    com.hinz.mybatis.mapper: debug
    com.hinz.mybatis.datasource.DynamicPlugin: debug






spring:
  datasource:
    write:
      username: root
      password: 123456
      url: jdbc:mysql://120.79.48.191:3306/write?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=true&autoReconnect=true
      driver-class-name: com.mysql.cj.jdbc.Driver
      jackson:
      date-format: yyyy-MM-dd HH:mm:ss
    read:
      username: root
      password: 123456
      url: jdbc:mysql://120.79.48.191:3306/read?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=true&autoReconnect=true
      driver-class-name: com.mysql.cj.jdbc.Driver
      jackson:
      date-format: yyyy-MM-dd HH:mm:ss

# 服务模块
devtools:
  restart:
    # 热部署开关
    enabled: true


